### ISSUE TITLE
Bitcoin ATM Sign

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#18]
I need a Design to show where a Bitcoin ATM is, I needed to be minimalist. 

Something like this (we don't need the Blink logo on it)

![Image](https://github.com/rudyblink/Blink-Design/assets/156244225/cbce162d-5f00-4e12-9fd3-71e1ced95071)

or a square figure

**Comment by Loicbtc** [comment]
https://www.figma.com/file/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?type=design&node-id=7519%3A5860&mode=design&t=EsHQQ5HMCh3RfPjQ-1

Find it here... 👆
