### ISSUE TITLE
Blog Post Design

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#19]
https://docs.google.com/document/d/1c-Poq-vHC0eJZF41FTaYZ0b5xU85eTi_XDqkdhdMtf8/edit?usp=sharing

**Comment by Loicbtc** [comment]
Blog post thumb : https://www.figma.com/file/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?type=design&node-id=7546%3A5871&mode=design&t=EsHQQ5HMCh3RfPjQ-1

Opengraph thumb : https://www.figma.com/file/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?type=design&node-id=7557%3A5911&mode=design&t=EsHQQ5HMCh3RfPjQ-1

IG Story : https://www.figma.com/file/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?type=design&node-id=7557%3A5935&mode=design&t=EsHQQ5HMCh3RfPjQ-1
