### ISSUE TITLE
New Currency Twitter post and Instagram story template

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#20]
We want to send a post every time we add a new currency on the app. 

It needs to be made as an announcement. 

Take a look at Andrew Message https://chat.galoy.io/galoy/pl/539xbfafyifrbxojxi69prehjc

**Comment by Loicbtc** [comment]
New currency added-twitter : https://www.figma.com/file/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?type=design&node-id=7560%3A6156&mode=design&t=nxTk5Xczfc25PP5y-1

New currency added-instagram-story : https://www.figma.com/file/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?type=design&node-id=7560%3A6731&mode=design&t=nxTk5Xczfc25PP5y-1
