### ISSUE TITLE
Pizza Day + Circles Challenge

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#21]
This is the May Blink Circles Challenge https://github.com/GaloyMoney/galoy-mobile/issues/3176 

We want a design similar as the one for the Halving, the design should have the synergy between pizza day and the challenge

**Comment by Loicbtc** [comment]
Pizza Day + Circles Challenge : https://www.figma.com/file/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?type=design&node-id=7655%3A5563&mode=design&t=OvKlqvVnICTj8m8j-1
