### ISSUE TITLE
Pizza Day Blog Post

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#22]
We need a design for this blog post https://docs.google.com/document/d/1URzNu-vbJvWYdxB43-XyRbWSc_aAqpUIegxWzx-1mZA/edit?usp=sharing 

Take a look at the blog, there is one image that also needs to be redesign to match Blink blog.

**Comment by Loicbtc** [comment]
Blogpost thumb : https://www.figma.com/file/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?type=design&node-id=7673%3A5742&mode=design&t=xIsxrvg08axM34KR-1
Opengraph thumb : https://www.figma.com/file/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?type=design&node-id=7676%3A5895&mode=design&t=xIsxrvg08axM34KR-1
IG Story : https://www.figma.com/file/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?type=design&node-id=7729%3A5563&mode=design&t=xIsxrvg08axM34KR-1
