### ISSUE TITLE
Blink Circles Challenge Story Format

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#23]
We need the blink circle challenge post on story format for IG

**Comment by Loicbtc** [comment]
Done : https://www.figma.com/file/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?type=design&node-id=7739%3A7218&mode=design&t=xIsxrvg08axM34KR-1

You can reopen the issue about it instead of created new one.
