### ISSUE TITLE
Blog Post Design

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#26]
https://docs.google.com/document/d/1tA3hSyMahFccH3agovSFlBasZwEFndAW917GrjGXQ6Q/edit?usp=sharing

**Comment by Loicbtc** [comment]
Blog post : https://www.figma.com/file/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?type=design&node-id=7864%3A21608&mode=design&t=hvsQ6lYXJFHzmCXu-1

Opengraph : https://www.figma.com/file/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?type=design&node-id=7884%3A28821&mode=design&t=hvsQ6lYXJFHzmCXu-1

IG Story : https://www.figma.com/file/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?type=design&node-id=7889%3A28838&mode=design&t=hvsQ6lYXJFHzmCXu-1
