### ISSUE TITLE
Blink Private Website Section

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#29]
![Image](https://github.com/rudyblink/Blink-Design/assets/156244225/6df58e97-5a39-4c44-804f-de4cf9d7a946)

**Comment by Loicbtc** [comment]
Download it on SVG format. 
The problem will be fixed.

**Comment by rudyblink** [comment]
> Download it on SVG format. The problem will be fixed.

Ok! We still need the image on the left.

**Comment by Loicbtc** [comment]
https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8204%3A6165&t=Sv0gif4KaaUyiO3F-1
