### ISSUE TITLE
Bounty Icon

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#30]
We ned a bounty icon for the website. 

![Image](https://github.com/rudyblink/Blink-Design/assets/156244225/2b77bea4-c1c7-4d20-bcae-803213869a77)

**Comment by Loicbtc** [comment]
https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8204%3A5983&t=Sv0gif4KaaUyiO3F-1
