### ISSUE TITLE
Blog Post Design - Open Source

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#31]
https://docs.google.com/document/d/136pzyBSzGGEUfI8OEWGvxcG3DF4JcI5S5WpT_fcSRMY/edit?usp=sharing

**Comment by Loicbtc** [comment]
Blogpost : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8413-19992&t=Bf6xY6odjenM0AFf-1

Opengraph : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8413-20016&t=Bf6xY6odjenM0AFf-1

IG Story : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8413-20087&t=Bf6xY6odjenM0AFf-1
