### ISSUE TITLE
Blog Post Design - ETFs

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#32]
https://docs.google.com/document/d/10v67ieLmGKbkzGU4R-oynwmVZskXJqQq2PYg016IE18/edit?usp=sharing

**Comment by Loicbtc** [comment]
Blogpost : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8413-20174&t=Bf6xY6odjenM0AFf-1

Opengraph : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8413-20182&t=Bf6xY6odjenM0AFf-1

IG Story : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8413-20194&t=Bf6xY6odjenM0AFf-1
