### ISSUE TITLE
Design for New Section on Blink Bounties Page

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#33]
![Image](https://github.com/rudyblink/Blink-Design/assets/156244225/870e0154-a1d4-4354-a567-c50bb2953aa5)

**Comment by Loicbtc** [comment]
https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8413-20226&t=Bf6xY6odjenM0AFf-1
