### ISSUE TITLE
We need 3 designs for the Buy and Sell Page

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#35]
1. Change the design of the first section in the Buy and Sell page. We need to add the Perú Flag 

![Image](https://github.com/rudyblink/Blink-Design/assets/156244225/6ccdc6c2-a7ec-431b-aa93-dd8a4a292d8b)

2. New Icon for the Buy and Sell in Peru eyebrow 

![Image](https://github.com/rudyblink/Blink-Design/assets/156244225/6296f012-85b0-44e0-b913-ca9094a82cec)

3. New design for the Peru section 

![Image](https://github.com/rudyblink/Blink-Design/assets/156244225/3406db33-702f-439e-9b86-195b56904495)

**Comment by Loicbtc** [comment]
1 : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8518-7832&t=YdtyrglEpF1UVGnx-1
2: https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8471-6309&t=XV77T6sY30JsKWzY-1

**Comment by Loicbtc** [comment]
icon : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8518-6428&t=YdtyrglEpF1UVGnx-1
