### ISSUE TITLE
Buy and Sell Story

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#36]
We need to update this design https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=6137-17687&t=ccYfhAliDLdyuZ8z-0 

The buy fee is now 0.3% and we also need one for sell. sell fee is 2%

**Comment by Loicbtc** [comment]
Buy : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8486-6336&t=XV77T6sY30JsKWzY-1
Sell : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8489-6383&t=XV77T6sY30JsKWzY-1
