### ISSUE TITLE
Blog post - Bitnob to Blink

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#38]
https://docs.google.com/document/d/1TetzGd1NRY6SivHyI_2NWN26byLdlRsxMB1nyaIjxeg/edit?usp=sharing

**Comment by Loicbtc** [comment]
Blogpost : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8751-6497&t=NK2lmM9cn4amWyru-1
Opengraph : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8751-6516&t=NK2lmM9cn4amWyru-1
IG Story : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8754-6551&t=NK2lmM9cn4amWyru-1
