### ISSUE TITLE
Twitter Space about Peru Expansion

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#39]
The design needs to be related to what we have been working on for Buy and Sell Perú

General information to display on the design: 

Date:  June 7

Time: 3:30 pm Peru time 

Participants: 

@bullishguate
@circogatto 
@JMayenTGU
@agentebtc

**Comment by Loicbtc** [comment]
https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8795-6481&t=J2EOIp7yruK2pK4I-1
