### ISSUE TITLE
New Buy Bitcoin Design

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#44]
we have a design this designs:

- https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=7020-2936&t=8HuHYQYrw1OxRFza-0
- https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=8500-6224&t=8HuHYQYrw1OxRFza-0 

The fee changed to 2%, we need to change that. Both English and Spanish

**Comment by Loicbtc** [comment]
https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=9063-21927&t=ywUqLwAl3VbU0JVb-1
EN : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=9063-21846&t=ywUqLwAl3VbU0JVb-1
ES : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=9063-21886&t=ywUqLwAl3VbU0JVb-1
