### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#46]
For IG story and Tweeter:
(I recommend you to translate it, so you know what I'm talking about) 

Si hubieras comprado $100 de bitcoin con tu aguinaldo hace un año 
  
     Hoy tendrías $196

Compra y Ahorra bitcoin

**Comment by Loicbtc** [comment]
Twiiter : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=9131-7455&t=nKEKuFsBGxiSmie7-1
IG Story : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=9131-7849&t=nKEKuFsBGxiSmie7-1
