### ISSUE TITLE
Blog post Design - Story and Twitter

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#49]
https://docs.google.com/document/d/18QgD-sYo2zFja8o7FWMBShExU-Eizi-C5Mcb2jKm0qE/edit?usp=sharing

**Comment by Loicbtc** [comment]
IG Story : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=9446-8122&t=WA18Q9hLzCHp6peQ-1

Twitter : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=9446-8041&t=WA18Q9hLzCHp6peQ-1

Opengraph : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=9446-7909&t=WA18Q9hLzCHp6peQ-1

Blogpost : https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=9446-7917&t=WA18Q9hLzCHp6peQ-1
