### ISSUE TITLE
Blink Circles Bounty - BUS

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#5]
We require a promotional design for our Blink Circles Bounty initiative. This challenge is designed for members of the Blink BUS Telegram group, who must adhere to specific requirements, submit their work, and, if selected as winners, receive rewards.  

https://docs.google.com/document/d/1k6wIBHTRehvJNmuvkfcna98yljareZlE5aeyrr3wnlI/edit?usp=sharing

**Comment by Loicbtc** [comment]
Need access to the doc.
