### ISSUE TITLE
Blink Fiat Flyer

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#53]
We need a flyer for new merchants to create awareness about our Buy and Sell service in El Salvador.

The flyer doesn't need much text; it should include:

- 'You can cash out Bitcoin to your bank account in El Salvador.'
- Monday to Friday: 8 am - 5 pm CST
Saturday: 8 am - 12 pm CST
- 2% commission
- 'Start accepting Bitcoin now'

The flyer should depict a merchant or someone making a payment, and the rest is up to your creativity.

**Comment by Loicbtc** [comment]
NOTED ! 
Will be out in the week-end.

**Comment by Loicbtc** [comment]
https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=9828-25121&t=8FaMLsNJkJdAIvtJ-1
