### ISSUE TITLE
Blink Instagram Live

### ISSUE THREAD

**Issue by rudyblink** [rudyblink/Blink-Design#54]
We want to promote our Instagram Live with Bitcoin Indonesia on Twitter and Instagram.

Information:

Thursday August 8th -- 21 pm EST 19 pm CST

Bitcoin Indonesia (use their logo) and Blink (use blink logo) 

Place: Instagram @blinkbtc_en

**Comment by Loicbtc** [comment]
Is the live about something else  ? 
Like, is there a topic for the live ?

**Comment by Loicbtc** [comment]
Need also bitcoin indonesia logo

**Comment by Loicbtc** [comment]
https://www.figma.com/design/eLxNsk3Sq18ffU3dFV2LXo/Blink-Brand-Assets?node-id=9907-11063&t=GEWCmjrPXa69Qg2a-1
